/**
 * Test Harness for MCP servers generated by mcp-forge
 * =====================================================
 * Validates that a generated server:
 * 1. Has required files (package.json/pyproject.toml, src/)
 * 2. Can be built/installed
 * 3. Responds to list_tools correctly
 * 4. Each tool has a valid inputSchema
 */

import { execSync } from 'child_process';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

export interface TestResult {
  passed: boolean;
  checks: { name: string; passed: boolean; message?: string }[];
}

export function testServer(serverDir: string): TestResult {
  const checks: { name: string; passed: boolean; message?: string }[] = [];

  // Detect language
  const isTs = existsSync(join(serverDir, 'package.json'));
  const isPy = existsSync(join(serverDir, 'pyproject.toml'));

  // Check 1: Required files exist
  if (isTs) {
    checks.push({
      name: 'package.json exists',
      passed: true,
    });
    checks.push({
      name: 'tsconfig.json exists',
      passed: existsSync(join(serverDir, 'tsconfig.json')),
      message: existsSync(join(serverDir, 'tsconfig.json')) ? undefined : 'Missing tsconfig.json',
    });
    checks.push({
      name: 'src/index.ts exists',
      passed: existsSync(join(serverDir, 'src', 'index.ts')),
      message: existsSync(join(serverDir, 'src', 'index.ts')) ? undefined : 'Missing src/index.ts',
    });
  } else if (isPy) {
    checks.push({
      name: 'pyproject.toml exists',
      passed: true,
    });
    checks.push({
      name: 'src/server.py exists',
      passed: existsSync(join(serverDir, 'src', 'server.py')),
      message: existsSync(join(serverDir, 'src', 'server.py')) ? undefined : 'Missing src/server.py',
    });
  } else {
    checks.push({
      name: 'Recognized project type',
      passed: false,
      message: 'No package.json or pyproject.toml found',
    });
  }

  // Check 2: Validate package metadata
  if (isTs) {
    try {
      const pkg = JSON.parse(readFileSync(join(serverDir, 'package.json'), 'utf-8'));
      const hasMcpSdk = !!pkg.dependencies && '@modelcontextprotocol/sdk' in pkg.dependencies;
      checks.push({
        name: 'package.json has MCP SDK dependency',
        passed: hasMcpSdk,
        message: hasMcpSdk ? undefined : 'Missing @modelcontextprotocol/sdk dependency',
      });
    } catch {
      checks.push({ name: 'package.json is valid JSON', passed: false, message: 'Invalid JSON' });
    }
  } else if (isPy) {
    const pyproject = readFileSync(join(serverDir, 'pyproject.toml'), 'utf-8');
    const hasMcpDep = pyproject.includes('mcp');
    checks.push({
      name: 'pyproject.toml has mcp dependency',
      passed: hasMcpDep,
      message: hasMcpDep ? undefined : 'Missing mcp dependency',
    });
  }

  // Check 3: Source code contains MCP server setup
  const srcFile = isTs
    ? join(serverDir, 'src', 'index.ts')
    : isPy
    ? join(serverDir, 'src', 'server.py')
    : null;

  if (srcFile && existsSync(srcFile)) {
    const src = readFileSync(srcFile, 'utf-8');
    const importsMcp = src.includes('modelcontextprotocol') || src.includes('mcp');
    const definesTools = src.includes('list_tools') || src.includes('ListTools');
    checks.push({
      name: 'Source imports MCP SDK',
      passed: importsMcp,
      message: importsMcp ? undefined : 'No MCP SDK imports found',
    });
    checks.push({
      name: 'Source defines tools',
      passed: definesTools,
      message: definesTools ? undefined : 'No tool definitions found',
    });
  }

  // Check 4: Dry-run build (optional, may fail if deps not installed)
  if (isTs && existsSync(join(serverDir, 'package.json'))) {
    try {
      execSync('npm install', { cwd: serverDir, stdio: 'pipe', timeout: 60000 });
      execSync('npm run build', { cwd: serverDir, stdio: 'pipe', timeout: 60000 });
      checks.push({ name: 'Build succeeds', passed: true });
    } catch (e) {
      checks.push({
        name: 'Build succeeds',
        passed: false,
        message: `Build failed: ${(e as Error).message}`,
      });
    }
  }

  const allPassed = checks.every((c) => c.passed);
  return { passed: allPassed, checks };
}
