/**
 * Scaffold logic for mcp-forge
 * ============================
 * Generates TS or Python MCP server projects from templates.
 */

import { mkdirSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';

export type Language = 'typescript' | 'python';
export type Template = 'read-only-api' | 'file-tool' | 'db-tool';

export interface ScaffoldOptions {
  name: string;
  lang: Language;
  template: Template;
  outDir: string;
}

const TEMPLATES: Record<Template, { title: string; description: string }> = {
  'read-only-api': {
    title: 'Read-Only API Wrapper',
    description: 'Wraps a read-only REST API as MCP tools.',
  },
  'file-tool': {
    title: 'File-Based Tool',
    description: 'Reads, writes, and searches files in a directory.',
  },
  'db-tool': {
    title: 'Database-Backed Tool',
    description: 'Queries a SQLite database via MCP tools.',
  },
};

function sanitizeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9_-]/g, '-').replace(/^-+|-+$/g, '');
}

function tsReadOnlyApi(name: string): Record<string, string> {
  const pkg = sanitizeName(name);
  return {
    'package.json': JSON.stringify({
      name: pkg,
      version: '0.1.0',
      description: `MCP server: ${TEMPLATES['read-only-api'].description}`,
      type: 'module',
      bin: { [pkg]: 'dist/index.js' },
      scripts: {
        build: 'tsc',
        start: 'node dist/index.js',
        test: 'node --test dist/**/*.test.js',
      },
      dependencies: {
        '@modelcontextprotocol/sdk': '^1.0.0',
      },
      devDependencies: {
        '@types/node': '^20.0.0',
        typescript: '^5.4.0',
      },
    }, null, 2),

    'tsconfig.json': JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        module: 'NodeNext',
        moduleResolution: 'NodeNext',
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
      },
      include: ['src/**/*'],
    }, null, 2),

    'src/index.ts': `#!/usr/bin/env node
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { ListToolsRequestSchema, CallToolRequestSchema } from "@modelcontextprotocol/sdk/types.js";

const server = new Server(
  { name: "${pkg}", version: "0.1.0" },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "fetch_data",
      description: "Fetch data from the API",
      inputSchema: {
        type: "object",
        properties: {
          endpoint: { type: "string", description: "API endpoint path" },
        },
        required: ["endpoint"],
      },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  if (request.params.name === "fetch_data") {
    const { endpoint } = request.params.arguments as { endpoint: string };
    // TODO: Implement actual API call
    return {
      content: [{ type: "text", text: \`Fetched from \${endpoint}\` }],
    };
  }
  throw new Error(\`Unknown tool: \${request.params.name}\`);
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch(console.error);
`,

    '.gitignore': 'node_modules/\ndist/\n*.log\n.env\n',
    'README.md': `# ${pkg}\n\nMCP server generated by mcp-forge.\n\n## Usage\n\n\`\`\`bash\nnpm install\nnpm run build\nnpm start\n\`\`\`\n`,
  };
}

function tsFileTool(name: string): Record<string, string> {
  const pkg = sanitizeName(name);
  const files = tsReadOnlyApi(name);
  files['src/index.ts'] = `#!/usr/bin/env node
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { ListToolsRequestSchema, CallToolRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { readFileSync, readdirSync, writeFileSync, existsSync } from "fs";
import { join } from "path";

const DATA_DIR = process.env.DATA_DIR || "./data";

const server = new Server(
  { name: "${pkg}", version: "0.1.0" },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "read_file",
      description: "Read a file from the data directory",
      inputSchema: {
        type: "object",
        properties: {
          path: { type: "string", description: "Relative file path" },
        },
        required: ["path"],
      },
    },
    {
      name: "list_files",
      description: "List files in the data directory",
      inputSchema: {
        type: "object",
        properties: {},
      },
    },
    {
      name: "write_file",
      description: "Write a file to the data directory",
      inputSchema: {
        type: "object",
        properties: {
          path: { type: "string" },
          content: { type: "string" },
        },
        required: ["path", "content"],
      },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const args = request.params.arguments as Record<string, string>;
  const filePath = join(DATA_DIR, args.path || "");

  switch (request.params.name) {
    case "read_file":
      if (!existsSync(filePath)) throw new Error(\`File not found: \${args.path}\`);
      return { content: [{ type: "text", text: readFileSync(filePath, "utf-8") }] };
    case "list_files":
      return { content: [{ type: "text", text: readdirSync(DATA_DIR).join("\\n") }] };
    case "write_file":
      writeFileSync(filePath, args.content);
      return { content: [{ type: "text", text: \`Wrote \${args.path}\` }] };
    default:
      throw new Error(\`Unknown tool: \${request.params.name}\`);
  }
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch(console.error);
`;
  return files;
}

function tsDbTool(name: string): Record<string, string> {
  const pkg = sanitizeName(name);
  const files = tsReadOnlyApi(name);
  files['package.json'] = JSON.stringify({
    name: pkg,
    version: '0.1.0',
    description: `MCP server: ${TEMPLATES['db-tool'].description}`,
    type: 'module',
    bin: { [pkg]: 'dist/index.js' },
    scripts: {
      build: 'tsc',
      start: 'node dist/index.js',
      test: 'node --test dist/**/*.test.js',
    },
    dependencies: {
      '@modelcontextprotocol/sdk': '^1.0.0',
      'better-sqlite3': '^9.0.0',
    },
    devDependencies: {
      '@types/better-sqlite3': '^7.6.0',
      '@types/node': '^20.0.0',
      typescript: '^5.4.0',
    },
  }, null, 2);

  files['src/index.ts'] = `#!/usr/bin/env node
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { ListToolsRequestSchema, CallToolRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import Database from "better-sqlite3";

const DB_PATH = process.env.DB_PATH || "./data.db";
const db = new Database(DB_PATH);

const server = new Server(
  { name: "${pkg}", version: "0.1.0" },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "query",
      description: "Run a SELECT query against the database",
      inputSchema: {
        type: "object",
        properties: {
          sql: { type: "string", description: "SQL SELECT statement" },
        },
        required: ["sql"],
      },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  if (request.params.name === "query") {
    const { sql } = request.params.arguments as { sql: string };
    if (!sql.trim().toLowerCase().startsWith("select")) {
      throw new Error("Only SELECT queries are allowed");
    }
    const rows = db.prepare(sql).all();
    return { content: [{ type: "text", text: JSON.stringify(rows, null, 2) }] };
  }
  throw new Error(\`Unknown tool: \${request.params.name}\`);
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch(console.error);
`;
  return files;
}

function pyReadOnlyApi(name: string): Record<string, string> {
  const pkg = sanitizeName(name).replace(/-/g, '_');
  return {
    'pyproject.toml': `[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "${pkg}"
version = "0.1.0"
description = "MCP server generated by mcp-forge"
requires-python = ">=3.10"
dependencies = ["mcp>=1.0.0"]

[project.scripts]
${pkg} = "${pkg}.server:main"
`,

    'src/__init__.py': '',
    'src/server.py': `#!/usr/bin/env python3
import asyncio
import os
from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import TextContent

server = Server("${pkg}")

@server.list_tools()
async def list_tools() -> list:
    return [
        {
            "name": "fetch_data",
            "description": "Fetch data from the API",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "endpoint": {"type": "string", "description": "API endpoint path"},
                },
                "required": ["endpoint"],
            },
        },
    ]

@server.call_tool()
async def call_tool(name: str, arguments: dict) -> list:
    if name == "fetch_data":
        endpoint = arguments.get("endpoint", "")
        # TODO: Implement actual API call
        return [TextContent(type="text", text=f"Fetched from {endpoint}")]
    raise ValueError(f"Unknown tool: {name}")

async def main():
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, server.create_initialization_options())

if __name__ == "__main__":
    asyncio.run(main())
`,

    '.gitignore': '__pycache__/\n*.egg-info/\ndist/\n.venv/\n.env\n',
    'README.md': `# ${pkg}\n\nMCP server generated by mcp-forge.\n\n## Usage\n\n\`\`\`bash\npip install -e .\n${pkg}\n\`\`\`\n`,
  };
}

function pyFileTool(name: string): Record<string, string> {
  const pkg = sanitizeName(name).replace(/-/g, '_');
  const files = pyReadOnlyApi(name);
  files['src/server.py'] = `#!/usr/bin/env python3
import asyncio
import os
from pathlib import Path
from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import TextContent

DATA_DIR = Path(os.environ.get("DATA_DIR", "./data"))
DATA_DIR.mkdir(exist_ok=True)

server = Server("${pkg}")

@server.list_tools()
async def list_tools() -> list:
    return [
        {
            "name": "read_file",
            "description": "Read a file from the data directory",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "path": {"type": "string", "description": "Relative file path"},
                },
                "required": ["path"],
            },
        },
        {
            "name": "list_files",
            "description": "List files in the data directory",
            "inputSchema": {"type": "object", "properties": {}},
        },
        {
            "name": "write_file",
            "description": "Write a file to the data directory",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "path": {"type": "string"},
                    "content": {"type": "string"},
                },
                "required": ["path", "content"],
            },
        },
    ]

@server.call_tool()
async def call_tool(name: str, arguments: dict) -> list:
    file_path = DATA_DIR / arguments.get("path", "")
    if name == "read_file":
        if not file_path.exists():
            raise ValueError(f"File not found: {arguments.get('path')}")
        return [TextContent(type="text", text=file_path.read_text())]
    elif name == "list_files":
        return [TextContent(type="text", text="\\n".join(f.name for f in DATA_DIR.iterdir()))]
    elif name == "write_file":
        file_path.write_text(arguments.get("content", ""))
        return [TextContent(type="text", text=f"Wrote {arguments.get('path')}")]
    raise ValueError(f"Unknown tool: {name}")

async def main():
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, server.create_initialization_options())

if __name__ == "__main__":
    asyncio.run(main())
`;
  return files;
}

function pyDbTool(name: string): Record<string, string> {
  const pkg = sanitizeName(name).replace(/-/g, '_');
  const files = pyReadOnlyApi(name);
  files['pyproject.toml'] = `[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "${pkg}"
version = "0.1.0"
description = "MCP server generated by mcp-forge"
requires-python = ">=3.10"
dependencies = ["mcp>=1.0.0"]

[project.scripts]
${pkg} = "${pkg}.server:main"
`;

  files['src/server.py'] = `#!/usr/bin/env python3
import asyncio
import os
import sqlite3
from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import TextContent

DB_PATH = os.environ.get("DB_PATH", "./data.db")

server = Server("${pkg}")

@server.list_tools()
async def list_tools() -> list:
    return [
        {
            "name": "query",
            "description": "Run a SELECT query against the database",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "sql": {"type": "string", "description": "SQL SELECT statement"},
                },
                "required": ["sql"],
            },
        },
    ]

@server.call_tool()
async def call_tool(name: str, arguments: dict) -> list:
    if name == "query":
        sql = arguments.get("sql", "").strip()
        if not sql.lower().startswith("select"):
            raise ValueError("Only SELECT queries are allowed")
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
        rows = conn.execute(sql).fetchall()
        conn.close()
        return [TextContent(type="text", text=str([dict(r) for r in rows]))]
    raise ValueError(f"Unknown tool: {name}")

async def main():
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, server.create_initialization_options())

if __name__ == "__main__":
    asyncio.run(main())
`;
  return files;
}

const TS_TEMPLATES: Record<Template, (name: string) => Record<string, string>> = {
  'read-only-api': tsReadOnlyApi,
  'file-tool': tsFileTool,
  'db-tool': tsDbTool,
};

const PY_TEMPLATES: Record<Template, (name: string) => Record<string, string>> = {
  'read-only-api': pyReadOnlyApi,
  'file-tool': pyFileTool,
  'db-tool': pyDbTool,
};

export function scaffold(opts: ScaffoldOptions): string {
  const targetDir = join(opts.outDir, opts.name);
  if (existsSync(targetDir)) {
    throw new Error(`Directory already exists: ${targetDir}`);
  }

  const templates = opts.lang === 'typescript' ? TS_TEMPLATES : PY_TEMPLATES;
  const files = templates[opts.template](opts.name);

  for (const [filePath, content] of Object.entries(files)) {
    const fullPath = join(targetDir, filePath);
    mkdirSync(join(fullPath, '..'), { recursive: true });
    writeFileSync(fullPath, content);
  }

  return targetDir;
}

export function listTemplates(): { id: Template; title: string; description: string }[] {
  return Object.entries(TEMPLATES).map(([id, t]) => ({ id: id as Template, ...t }));
}
